# Generated by Django 5.1.2 on 2024-11-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.TextField()),
                ('c_name', models.TextField()),
                ('dis', models.TextField()),
                ('duration', models.IntegerField()),
                ('Course_fees', models.IntegerField()),
                ('offer_fees', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
            ],
        ),
    ]
